import type { AiProviderConfig } from './provider-types';

export const DEFAULT_AI_PROVIDERS: AiProviderConfig[] = [
  {
    apiStyle: 'openai-responses',
    baseUrl: 'https://api.openai.com/v1',
    defaultModelId: 'gpt-5.5',
    enabled: false,
    id: 'openai',
    models: [
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'gpt-5.5',
        name: 'GPT-5.5',
      },
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'gpt-5.4',
        name: 'GPT-5.4',
      },
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools'],
        enabled: true,
        id: 'gpt-5.4-mini',
        name: 'GPT-5.4 mini',
      },
    ],
    name: 'OpenAI',
    secretStatus: 'missing',
    type: 'openai',
  },
  {
    apiStyle: 'anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    defaultModelId: 'claude-sonnet-4-6',
    enabled: false,
    id: 'anthropic',
    models: [
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'claude-opus-4-7',
        name: 'Claude Opus 4.7',
      },
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
      },
      {
        capabilities: ['text', 'vision', 'tools'],
        enabled: true,
        id: 'claude-haiku-4-5',
        name: 'Claude Haiku 4.5',
      },
    ],
    name: 'Anthropic',
    secretStatus: 'missing',
    type: 'anthropic',
  },
  {
    apiStyle: 'openai-compatible',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModelId: 'openrouter/auto',
    enabled: false,
    id: 'openrouter',
    models: [
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'openrouter/auto',
        name: 'OpenRouter Auto',
      },
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools'],
        enabled: true,
        id: 'openai/gpt-5.5',
        name: 'GPT-5.5',
      },
    ],
    name: 'OpenRouter',
    secretStatus: 'missing',
    type: 'openai-compatible',
  },
  {
    apiStyle: 'google',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    defaultModelId: 'gemini-3.1-pro-preview',
    enabled: false,
    id: 'google',
    models: [
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'gemini-3.1-pro-preview',
        name: 'Gemini 3.1 Pro Preview',
      },
      {
        capabilities: ['text', 'vision', 'tools'],
        enabled: true,
        id: 'gemini-3-flash-preview',
        name: 'Gemini 3 Flash Preview',
      },
    ],
    name: 'Google',
    secretStatus: 'missing',
    type: 'google',
  },
  {
    apiStyle: 'openai-compatible',
    baseUrl: 'https://api.deepseek.com',
    defaultModelId: 'deepseek-v4-pro',
    enabled: false,
    id: 'deepseek',
    models: [
      {
        capabilities: ['text', 'reasoning', 'tools'],
        enabled: true,
        id: 'deepseek-v4-pro',
        name: 'DeepSeek V4 Pro',
      },
      {
        capabilities: ['text', 'reasoning', 'tools'],
        enabled: true,
        id: 'deepseek-v4-flash',
        name: 'DeepSeek V4 Flash',
      },
    ],
    name: 'DeepSeek',
    secretStatus: 'missing',
    type: 'openai-compatible',
  },
  {
    apiStyle: 'openai-compatible',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModelId: 'qwen3.6-plus',
    enabled: false,
    id: 'qwen',
    models: [
      {
        capabilities: ['text', 'vision', 'reasoning', 'tools', 'web'],
        enabled: true,
        id: 'qwen3.6-plus',
        name: 'Qwen3.6 Plus',
      },
      {
        capabilities: ['text', 'tools'],
        enabled: true,
        id: 'qwen3-coder-plus',
        name: 'Qwen3 Coder Plus',
      },
    ],
    name: 'Qwen',
    secretStatus: 'missing',
    type: 'openai-compatible',
  },
  {
    apiStyle: 'openai-compatible',
    baseUrl: 'http://localhost:11434/v1',
    defaultModelId: 'llama3.3',
    enabled: false,
    id: 'ollama',
    models: [
      { capabilities: ['text'], enabled: true, id: 'llama3.3', name: 'Llama 3.3' },
      { capabilities: ['text'], enabled: true, id: 'qwen3:32b', name: 'Qwen3 32B' },
    ],
    name: 'Ollama',
    secretStatus: 'notRequired',
    type: 'ollama',
  },
];
